basedir: /path/to/cap-tcr/
barcodes: /IDT_barcodesNovaSeq.txt
extract_barcodes_path: /source/extract_barcodes.py
inputdir: /mixcr/input/
aligndir: /mixcr/align/
logdir: /mixcr/log/
clonetrack: /source/clonetrack.R
pars_log: /source/parse_log.py
mixcr_path: /source/mixcr.jar
chain: TRA
pattern: FAS
