basedir: /mnt/work1/users/pughlab/src/cap-tcr-snakemake/
barcodes: /mnt/work1/users/pughlab/src/cap-tcr-snakemake/captcr-snakemake-main/IDT_barcodesNovaSeq.txt
extract_barcodes_path: /mnt/work1/users/pughlab/src/cap-tcr-snakemake/captcr-snakemake-main/source/extract_barcodes.py
inputdir: /mnt/work1/users/pughlab/src/cap-tcr-snakemake/mixcr/input/
aligndir: /mnt/work1/users/pughlab/src/cap-tcr-snakemake/mixcr/align/
logdir: /mnt/work1/users/pughlab/src/cap-tcr-snakemake/mixcr/log/
clonetrack: /mnt/work1/users/pughlab/src/cap-tcr-snakemake/captcr-snakemake-main/source/clonetrack.R
pars_log: /mnt/work1/users/pughlab/src/cap-tcr-snakemake/captcr-snakemake-main/source/parse_log.py
mixcr_path: /mnt/work1/users/pughlab/src/cap-tcr-snakemake/captcr-snakemake-main/source/mixcr.jar
chain: TRA
pattern: FAS
